apiVersion: v1
kind: Service
metadata:
  name: springboot-gke
  labels:
    app: hello
    tier: web
    'backstage.io/kubernetes-id': springboot-project
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello
    tier: web